config/routes.rb
AOMVotingApp2::Application.routes.draw do
  resources :votes

  resources :members
    post  '/valid_member' => 'members#valid_member'
    get   '/admin/appReboot' => 'members#appReboot'
    get  '/admin/totalRecall' => 'members#totalRecall'
    post  '/admin/appReboot' => 'members#appReboot'

  resources :nominees
    get '/candidate_selection' => 'nominees#candidate_selection'
    get '/chairman_selection' => 'nominees#chairman_selection'
    get '/chairman_reviewal' => 'nominees#chairman_reviewal'
    get '/fellows_vote' => 'nominees#fellows_vote'
    post '/fellows_vote' => 'nominees#fellows_vote'
    get '/results' => 'nominees#results'
    get '/success' => 'nominees#success'

  

end

app/models/nominee.rb
class Nominee < ActiveRecord::Base
	belongs_to :member
	has_many :votes, foreign_key: "vote_id"

	validates :mail, :name, :cv, :statement, :nominator_mail, presence: true
	validates_format_of :mail, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "doesn't look like an email address" 
	validates :mail, :uniqueness => { :message => " Warning! - That email belongs to a fellow that was already nominated" }
	validates :nominator_mail, :uniqueness => { :case_sensitive => false, :message => " Warning! - You already submitted a nomination" }
	validates_format_of :nominator_mail, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "doesn't look like an email address" 
	validate :nominator_mail_is_valid

# Custom validators

	def nominator_mail_is_valid
		@member = Member.all
		@count = 0
	    @member.each do |f|
	      if f.mail.downcase == nominator_mail.downcase
	      	@count = 1
	      end
	    end
	    if @count == 0
	    	errors.add(:nominator_mail, "This email address does not exist in our records. Please contact the administrator")
	    end
	end


end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :set_nominee, only: [:show, :edit, :update, :destroy]

  # GET /nominees
  # GET /nominees.json
  def index
    @nominees = Nominee.all
  end

  # GET /nominees
  # GET /nominees.json
  def chairman_reviewal
    @nominees = Nominee.all
  end

  # GET /candidate_selection
  def candidate_selection
    @nominees = Nominee.all
  end

  # GET /chairman_selection
  def chairman_selection
    @nominees = Nominee.all
  end

  # GET/POST /fellows_vote
  def fellows_vote
    # initializers
    @nominees = Nominee.all
    @votes = Vote.all
    @members = Member.all
    # @isValid is used as a flag to identify if the email entered matches one of the Members
    @isValid = false
    # @voted is used as a flag to know if that member has already voted.
    @voted = false
    #email inputted by the user
    mail = params["email"] 

    # visit every member to see if the email mathes a member
    @members.each do |member|
      # Case in which the email is validated
      if member.mail.eql?(mail)
        # Email was validated and member has not voted yet
        # The email is added to the @votedArray
        puts "------------- mail is valid --------------"
        if member.voted == nil || member.voted == false
          @isValid = true
          member.update(:voted => true)
          puts "------------- mail hasnt voted --------------"
        else
          # Email was validated but member had already voted
          @isValid = true
          @voted = true
          puts "------------- mail has voted --------------"
        end
      end
    end
  end

  # GET /results
  def results
    @nominees = Nominee.all
    @votes = Vote.all
    @members = Member.all
    @votersCount = 0

    # Get the total number of members who voted
    @members.each do |member|
      if member.voted
        @votersCount += 1
      end
    end
  end

  #def success
  #end

  # GET /nominees/1
  # GET /nominees/1.json
  def show
  end

  # GET /nominees/new
  def new
    @nominee = Nominee.new
  end

  # GET /nominees/1/edit
  def edit
  end

  # POST /nominees
  # POST /nominees.json
  def create
    @nominee = Nominee.new(nominee_params)

    respond_to do |format|
      if @nominee.save
        format.html { redirect_to @nominee, notice: 'Nominee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nominee }
        #format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nominees/1
  # PATCH/PUT /nominees/1.json
  def update
    
    @nominees = Nominee.all

    # For candidate_selection view. 
    # Update the nominee check count
    @check = "0"
    @check = params[:nominee]["committee_check"].to_i
    puts "nominee id: #{@nominee.id}"
    puts "check count: #{@nominee.committee_check_count}"
    puts "Check = #{@check} "
    if @check == 1
      if @nominee.committee_check_count == nil
        @nominee.committee_check_count = 1
      else
        @nominee.committee_check_count += 1
      end
      puts "check count: #{@nominee.committee_check_count}"
    else 
      # If this candidate was NOT checked and it was previously approved then keep its value in true
      puts "------------@check = 0-------#{@check}"
      if @nominee.committee_check
        puts "------------@check = 0-------#{@check}"
        params[:nominee]["committee_check"] = "1"
        puts "------------@check = 0-------#{params[:nominee]["committee_check"]}"
      end
    end
   

    # For Fellows_vote view. 
    # A vote is received. Update the nominee vote count
    @voted = params[:nominee]["vote_id"].to_i
    if @voted > 0
      puts "vote id = #{@voted} and nominee id = #{params[:id]}"
      myNom = Nominee.find_by_id(params[:id].to_i)
      puts "nominee.confirmed = #{myNom}"
      
      # vote recieved is "Confirmed" type
      if @voted == 1
        if myNom["confirmed"] == nil
          Nominee.update(params[:id].to_i, :confirmed => 1)
        else
          count = myNom["confirmed"] + 1
          Nominee.update(params[:id].to_i, :confirmed => count)
        end
      end

      # vote recieved is "Not Confirmed" type
      if @voted == 2
        if myNom["not_confirmed"] == nil
          Nominee.update(params[:id].to_i, :not_confirmed => 1)
        else
          count = myNom["not_confirmed"] + 1
          Nominee.update(params[:id].to_i, :not_confirmed => count)
        end
      end

      # vote recieved is "Abstained" type - Note: this column is of type string
      if @voted == 3
        if myNom["abstained"] == nil
          Nominee.update(params[:id].to_i, :abstained => 1.to_s)
        else
          count = myNom["abstained"].to_i + 1
          Nominee.update(params[:id].to_i, :abstained => count.to_s)
        end
      end
    end

    respond_to do |format|
      if @nominee.update(nominee_params)
        format.html { redirect_to @nominee, notice: 'Nominee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nominees/1
  # DELETE /nominees/1.json
  def destroy
    @nominee.destroy
    respond_to do |format|
      format.html { redirect_to nominees_url }
      format.json { head :no_content }
    end
  end

  # DELETE ALL Nominees
  def destroy_all
    Nominee.delete_all
    respond_to do |format|
      format.html { redirect_to nominees_url }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nominee
      @nominee = Nominee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nominee_params
      params.require(:nominee).permit(:nominator_mail, :member_id, :mail, :name, :cv, :statement, :committee_check, :committee_check_count, :chairman_check, :confirmed, :not_confirmed, :abstained, :id, :vote_id)
    end
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/views/nominees/_form.html.erb
<%= simple_form_for(@nominee) do |f| %>

  <div class="field">
    <br><%= f.input :nominator_mail, label: 'My email is:', placeholder: 'Your email is for validation purpose only'%><br>
  </div>
  <div class="field">
    <%= f.input :name, label: 'I would like to nominate:', placeholder: 'Jane Doe'%><br>
  </div>
  <div class="field">
    <%= f.input :mail, as: :email, label: 'Her/His email is:', placeholder: 'janedoe@mail.com' %><br>
  </div>
  <div class="field">
    <%= f.input :cv, as: :text, label: 'Paste nominee\'s CV here:', placeholder: 'IMPORTANT: MAKE SURE TO USE A LEFT JUSTIFIED CV TO AVOID FORMATTING ISSUES.' %><br>
  </div>
  <div class="field">
  <%= f.input :statement, as: :text, label: 'Paste nominee\'s supporting statement here:', placeholder: 'Type here the statement of purpose for your nomination ' %><br><br>
  </div>
  <div class="myButton">
    <%= f.submit "Submit Nomination", :class => 'btn btn-primary btn-fill'%>
  </div>
<% end %>

app/views/nominees/candidate_selection.html.erb
<h2 id="title">Candidate Selection</h2><br>
<div class="container-fluid" id="box">
  <div class="table-responsive">
    <table class="table table-hover" id="nomineeTable">
      <thead>
        <tr>
          <th>#</th>
          <th>Approve</th>
          <th>Nominee Name</th>
          <th>Supporting Documents</th>
        </tr>
      </thead>
      <% @count = 0 %> <!-- This count is to enumerate each row of the table -->
      <% @nominees = @nominees.order("name") %>
      <!-- Loop through the nominees table to display each one in a different row  -->
      <% @nominees.each do |nominee| %>
      <tr>
      <% @count = @count + 1 %>
      <!-- @index helps to keep track of the checkbox id within the array of checkboxes -->
      <% @index = @count - 1 %>
      <%= bootstrap_form_for nominee, :action => 'candidate_selection', layout: :inline, remote: true do |f| %>
    
        <td class="td"><%= @count %></td>
        <td><%= f.check_box :committee_check, label: " ", hide_label: true, :checked => false, :class => "taskCheckbox", :onChange => "javascript: if($('.taskCheckbox')[#{@index}].checked){if(!sure()){$('.taskCheckbox')[#{@index}].checked = false;}};" %>
        </td>
        <td class="td"><%= nominee.name %></td>
        <td>
          <!-- Button trigger modal -->
         <a href="#myModal<%= nominee.id%>" role="button" class="center" data-toggle="modal">View Details</a>          <!-- Modal -->
            
            <div class="modal fade" id="myModal<%= nominee.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title" id="myModalLabel">Details for:  <%= nominee.name %></h3>
                  </div><br>
                  <div class="container-fluid" align="justify">
                    <div class="row">
                      <div class="col-md-6">
                        <p>
                          <strong>Nominee Mail:</strong>
                          <%= nominee.mail %>
                        </p>
                      </div>
                    <br>  
                    </div>
                    <div class="row">  
                      <div class="col-md-12">
                        <p><strong>Nominee Statement:</strong></p>
                        <textarea id="statement" class="form-control" rows="5">
                          <%= nominee.statement %>
                        </textarea>
                      </div>
                    </div>  
                    <br>
                    <div class="row">  
                      <div class="col-md-12">
                        <p><strong>Nominee Curriculum Vitae:</strong></p>
                        <textarea id="cv" class="form-control" rows="20">
                          <%= nominee.cv %>
                        </textarea>
                      </div>
                    </div>
                    <br>
                  </div>
                </div>
              </div>
            </div>
        </td>
      <% end %>
      </tr>
      <script type="text/javascript">
        var sure = function() {
          var reply = confirm("Are you sure you want to approve this nominee?");
          if (reply) {return true;}
        };
      </script>
      <% end %>
    </table>
    <div class="center">
      <%= submit_tag "Submit Approvals", :class => "btn btn-primary btn-lg", :id => "approve", :data => {:disable_with => "Saving..."} %>
    </div>
    <div class="modal fade" id="submitModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <h3 style="text-align: center;">...Submitting your approvals.</h3>
            <h3 style="text-align: center;">Please wait.</h3>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  </div>
</div>

app/views/nominees/chairman_reviewal.html.erb
<h2 id="title">Chairman Reviewal Site</h2>
<div class="container-fluid" id="box">
  <div class="table-responsive">
    <table class="table table-hover" id="comcheckTable">
        <thead>
          <tr>
            <th colspan="1">#</th>
            <th colspan="1">Name</th>
            <th colspan="1">Mail</th>
            <th colspan="1">Nominator</th>
            <th colspan="1">Documents</th>
            <th colspan="1">Approved by Committee</th>
            <th colspan="1"># of Approvals</th>
            
          </tr>
        </thead>
        <tbody>
        <% @count = 0 %>
        <% @nominees = @nominees.order("committee_check_count DESC") %>
          <% @nominees.each do |nominee| %>
            <%= simple_form_for(nominee, :html => {:multipart => true, :class => '.form-inline'}) do |f| %>
              <tr>
                <% @count += 1 %>
                <td><%= @count %></td>   
                <td><%= nominee.name %></td>        
                <td><%= nominee.mail %></td>
                <td><%= nominee.nominator_mail %></td>
                <td class="td">
                    <!-- Button trigger modal -->
                   <a href="#myModal<%= nominee.id%>" role="button" class="center" data-toggle="modal">View</a>          <!-- Modal -->
                      <div class="modal fade" id="myModal<%= nominee.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                              <h3 class="modal-title" id="myModalLabel">Details for:  <%= nominee.name %></h3>
                            </div><br>
                            <div class="container-fluid" align="justify">
                              <div class="row">
                                <div class="col-md-6">
                                  <p>
                                    <strong>Nominee Mail:</strong>
                                    <%= nominee.mail %>
                                  </p>
                                </div>
                              <br>  
                              </div>
                              <div class="row">  
                                <div class="col-md-12">
                                  <p><strong>Nominee Statement:</strong></p>
                                  <textarea id="statement" class="form-control" rows="5">
                                    <%= nominee.statement %>
                                  </textarea>
                                </div>
                              </div>  
                              <br>
                              <div class="row">  
                                <div class="col-md-12">
                                  <p><strong>Nominee Curriculum Vitae:</strong></p>
                                  <textarea id="cv" class="form-control" rows="20">
                                    <%= nominee.cv %>
                                  </textarea>
                                </div>
                              </div>
                              <br>
                            </div>
                          </div>
                        </div>
                      </div>
                </td>
                <!-- End of the modal-->
                <td><%= nominee.committee_check %></td>
                <td><%= nominee.committee_check_count %></td>
                
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <br>
      
    </div>
</div>

app/views/nominees/chairman_selection.html.erb
<h2 id="title">Chairman Selection</h2><br>
<div class="container-fluid" id="box">
  <div class="jumbotron">
    <button type="button" id="jumboclose" class="close" aria-hidden="true">&times; dismiss</button>
    <h3>Notes:</h3>
    <h4>1. To confirm a nominee into the final stage please click the checkbox mathing her/his name. A message will pop asking you to confirm that selection. </h4>
    <h4>2. # Pre-Approvals corresponds to the number of committe members that approved that specific nominee</h4>
  </div>
  <div class="container-fluid" id="collapsed">
    <button type="button" id="jumboclose" class="close" aria-hidden="true">
    <span class="caret"></span>Notes</button>
  </div><br>
  <div class="table-responsive">
    <table class="table table-hover" id="nomineeTable">
      <thead>
        <tr>
          <th>Check</th>
          <th># Pre-Approvals</th>
          <th>Nominee Name</th>
          <th>Supporting Documents</th>
        </tr>
      </thead>
      <% @count = 0 %> <!-- This count is to enumerate each row of the table -->
      <% @nominees = @nominees.order("committee_check_count DESC") %>
      <!-- Loop through the nominees table to display each one in a different row  -->
      <% @nominees.each do |nominee| %>
      <!-- Since we at this stage only the nominees preselected by the committe have advanced
            then we must check that only nominees with committee_check == true are shown -->
        <% if nominee.committee_check %>
          <tr>
          <% @count = @count + 1 %>
          <!-- @index helps to keep track of the checkbox id within the array of checkboxes -->
          <% @index = @count - 1 %>
          <%= form_for(nominee, id: 'checkbox_form', remote: true, :html => {:multipart => true, :class => 'form-inline'}) do |f| %>
            <td><%= f.check_box :chairman_check, as: :boolean, boolean_style: :inline, :checked => false, label: false, :class => "taskCheckbox", :onChange => "javascript: if($('.taskCheckbox')[#{@index}].checked){if(sure()){$(this.form).submit();}else{$('.taskCheckbox')[#{@index}].checked = false;}};" %>
              <% end %> <!-- End of the form -->
            </td>
            <td class="center"><%= nominee.committee_check_count %></td>
            <td class="td"><%= nominee.name %></td>
            <td class="td">
              <!-- Button trigger modal -->
             <a href="#myModal<%= nominee.id%>" role="button" class="center" data-toggle="modal">View Details</a>          <!-- Modal -->
                <div class="modal fade" id="myModal<%= nominee.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h3 class="modal-title" id="myModalLabel">Details for:  <%= nominee.name %></h3>
                      </div><br>
                      <div class="container-fluid" align="justify">
                        <div class="row">
                          <div class="col-md-6">
                            <p>
                              <strong>Nominee Mail:</strong>
                              <%= nominee.mail %>
                            </p>
                          </div>
                        <br>  
                        </div>
                        <div class="row">  
                          <div class="col-md-12">
                            <p><strong>Nominee Statement:</strong></p>
                            <textarea id="statement" class="form-control" rows="5">
                              <%= nominee.statement %>
                            </textarea>
                          </div>
                        </div>  
                        <br>
                        <div class="row">  
                          <div class="col-md-12">
                            <p><strong>Nominee Curriculum Vitae:</strong></p>
                            <textarea id="cv" class="form-control" rows="20">
                              <%= nominee.cv %>
                            </textarea>
                          </div>
                        </div>
                        <br>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- End of the modal-->
            </td>
        
      <% end %> <!-- End of the if -->
      </tr>
      <!-- This java script asks for confirmation when checking/submitting the approval of a nominee -->
      <script type="text/javascript">
        var sure = function() {
          var reply = confirm("Are you sure you want to approve this nominee?");
          if (reply) {return true;}
        };
      </script>
      <% end %> <!-- End of for -->
    </table>
  </div>
</div>

app/views/nominees/edit.html.erb
<h3 id="title">Edit Nominee</h3>

<div class="tab-content">
    <div class="container-fluid" id="about">
      <div class="row">
          <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
				<%= render 'form' %>
			</div>
	    </div>
	</div>
</div>

app/views/nominees/fellows_vote.js.erb
// Check if the email is valid and if the member has voted already to display
// the voting table
$('#voted').hide();
$('#invalid').hide();
$('#votingTable').hide();
if(<%= @isValid %>){
	if(<%= @voted %>){
		$('#voted').show();
		$('#votingTable').hide();
		$('.table-responsive').show(); //Left intentionally for edge cases where someone may need this
	}else {
		$('.table-responsive').show();
	}
}
else{
	$('#invalid').show();
};

app/views/nominees/index.html.erb
<h2 id="title">Nominees</h2>
<div class="container-fluid" id="box">
  <div class="table-responsive">
    <table class="table table-hover" id="allNomTable">
        <thead>
          <tr>
            <th colspan="1">#</th>
            <th colspan="1">Nominator_Mail</th>
            <th colspan="1">Nominee_Mail</th>
            <th colspan="1">Nominee_Name</th>
            <th colspan="1">Documents</th>
            <th colspan="1">Com.Check</th>
            <th colspan="1">Com.Count</th>
            <th colspan="1">Chairman Check</th>
            <th colspan="1">Confirmed</th>
            <th colspan="1">Not Confirmed</th>
            <th colspan="1">Abstained</th>
          </tr>
        </thead>
        <tbody>
        <% @count = 0 %>
        <% @nominees = @nominees.order("committee_check_count DESC") %>
          <% @nominees.each do |nominee| %>
            <%= simple_form_for(nominee, :html => {:multipart => true, :class => '.form-inline'}) do |f| %>
              <tr>
                <% @count += 1 %>
                <td><%= @count %></td>
                <td><%= nominee.nominator_mail %></td>
                <td><%= nominee.mail %></td>
                <td><%= nominee.name %></td>
                <td class="td">
                    <!-- Button trigger modal -->
                   <a href="#myModal<%= nominee.id%>" role="button" class="center" data-toggle="modal">View Details</a>          <!-- Modal -->
                      <div class="modal fade" id="myModal<%= nominee.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                              <h3 class="modal-title" id="myModalLabel">Details for:  <%= nominee.name %></h3>
                            </div><br>
                            <div class="container-fluid" align="justify">
                              <div class="row">
                                <div class="col-md-6">
                                  <p>
                                    <strong>Nominee Mail:</strong>
                                    <%= nominee.mail %>
                                  </p>
                                </div>
                              <br>  
                              </div>
                              <div class="row">  
                                <div class="col-md-12">
                                  <p><strong>Nominee Statement:</strong></p>
                                  <textarea id="statement" class="form-control" rows="5">
                                    <%= nominee.statement %>
                                  </textarea>
                                </div>
                              </div>  
                              <br>
                              <div class="row">  
                                <div class="col-md-12">
                                  <p><strong>Nominee Curriculum Vitae:</strong></p>
                                  <textarea id="cv" class="form-control" rows="20">
                                    <%= nominee.cv %>
                                  </textarea>
                                </div>
                              </div>
                              <br>
                            </div>
                          </div>
                        </div>
                      </div>
                </td>
                <!-- End of the modal-->
                <td><%= nominee.committee_check %></td>
                <td><%= nominee.committee_check_count %></td>
                <td><%= nominee.chairman_check %></td>
                <td><%= nominee.confirmed %></td>
                <td><%= nominee.not_confirmed %></td>
                <td><%= nominee.abstained %></td>
                <td><%= link_to 'Show', nominee %></td>
                <td><%= link_to 'Edit', edit_nominee_path(nominee) %></td>
                <td><%= link_to 'Destroy', nominee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <br><br>
      <div class="center">
        <h4>To nominate someone please click the "New Nominee" button below </h4>
        <h4>and follow the instructions</h4>
        <%= link_to 'New Nominee', new_nominee_path, class: "btn btn-primary", style: "color: white;" %>
      </div>
    </div>
</div><br><br><br>
<div id="year">
  <p>_</p>
</div>

app/views/nominees/new.html.erb
<h2 id="title">Fellow Nomination</h2>

<div class="tab-content">
    <div class="container-fluid" id="about">
      <div class="row">
          <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
				<%= render 'form' %>
			</div>
	    </div>
	</div>
</div>

app/views/nominees/show.html.erb
<div class="alert alert-success" role="alert">
  <ul>
      <li><%= notice %></li>
      <h4>Thank you for nominating <%= @nominee.name %>!</h4>
      <p>Use the edit button at the bottom of this page to make any modification needed.</p>
  </ul>
</div>

<div class="container-fluid" align="justify">
  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Nominee Name:</strong>
        <%= @nominee.name %>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Nominee Mail:</strong>
        <%= @nominee.mail %>
      </p>
    </div>
  <br>  
  </div>
  <div class="row">  
    <div class="col-md-12">
      <p><strong>Nominee Statement:</strong></p>
      <textarea id="statement" class="form-control" rows="5">
        <%= @nominee.statement %>
      </textarea>
    </div>
  </div>  
  <br>
  <div class="row">  
    <div class="col-md-12">
      <p><strong>Nominee Curriculum Vitae:</strong></p>
      <textarea id="cv" class="form-control" rows="15">
        <%= @nominee.cv %>
      </textarea>
    </div>
  </div>
  <br>
  <%= link_to 'Edit', edit_nominee_path(@nominee) %>
</div>

app/views/nominees/success.html.erb
<div class="container-fluid">
	<br><br><br>
	<div class="alert alert-success" role="alert">
		<h2 style="text-align: center;"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Thank you for using the AOM Fellows Voting App!</h2>
		<h3 style="text-align: center;"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Your submission has been succesfully recorded.</h3>
	</div>
	<br><br><br>
</div>

app/views/nominees/update.js.erb
//<% @check == "1" %>